---
title: "All the books in the world worth reading"
author: Arturo
format:
  html:
    css: posts_styles.css
---

It was a Wednesday morning like any other for 12-year-old Donald Green. He was awoken by the memory of his sister’s alarm-clock. Although a quiet and comforting thought, it was eerie how some days he could also hear the footsteps it used to precede. She was in college now, had been for almost a year studying Anthropology or something like that. Just a few seconds later, his hand extended from underneath the covers feeling for his own alarm-clock ringing. The room was dark and damp, the top bunk empty as it had been for weeks, and the air smelled faintly of white-board markers. He was never prepared but it always arrived, the morning urge to evacuate, as his dad called it. An upside of his sister leaving was that he had freedom to use the toilet on the first floor instead of the freezing cold one on the ground. There was always this moment of calm emergency in the morning, when Don squared off with two opposing forces, the fullness of his bladder and the inertia of sleep. He revelled in this moment every morning since the top bunk became empty, willing to debate both angel and devil in exchange for a few more minutes of oblivion.

—–

Don’s parents sat in the kitchen, reading and sipping on coffee. The stairs from first to ground floor were made of stone and Don felt the cold through his socks. He liked having breakfast with his parents, although they rarely talked much. Everyone minded their own business as long as Don was reading and not on his phone. Halfway through his cereal bowl and blood-orange, Don’s mom spoke. ‘‘Donnie please, ask Ms. Rider for all his evaluations and make sure that she shows you his desk as well.’’ Don was surprised but did not protest, it made sense for him to pick up his brother’s possessions, he had gone to the same school of course. His mother always struck him as a very efficient woman, his dad more the dreamy type. ‘‘And don’t forget to check his locker son, I know he had books in there. Take this extra backpack. It’s old, but big enough.’’ Don spooned the sweet juice of the blood-orange from the deep end of the bowl and returned to his room to shower and get dressed for his school-day.

—–

Hellman-Reese Middle-School was a single building between the athletics grounds and the High-School building of the same name. It stood flat and boring compared to the recently renovated nursery igloo and the colourful 400m athletics track. Don had heard friends discuss nurse-proof plans to gain some unscheduled nap time in the infirmary, and brag about missing class like it was some kind of big deal. Today, Don would have the perfect excuse, but he did not even contemplate using the task as a legitimate cause to skip, because it wasn’t. His brother would have been happy with Don’s unconscious and conscientious mind. So, Don ran to the school cafeteria and devoured his breaded chicken, gulped his glass of milk and vanished the dessert banana into his trouser pockets. This would give him all of lunch time and recess to collect his brother’s things.

Don approached Ms Rider, who took him through the high-school gates and into the administrative offices where he started filling the old empty bag with the contents of his brother’s desk. ‘‘And how are your parents doing?’’ She asked. ‘‘Both are well, my mom is working at home now … uh … from home I mean, I think they are building something in her office.’’ The backpack was a quarter full now and Don was filling one of the folders he had brought with loose papers from the desk. ‘‘We all miss him you know. I have talked to other teachers and students and there is no one who knew him who does not feel something is gone’’. Ms Rider would have watched herself with any other 12-year-old, but as the school’s principal counsellor she knew how precociously wise and tough Don was, much like his brother. ‘‘You know you can always come to me if you don’t want to talk about it with your parents.’’ ‘‘Yeah, I know Ms Rider, I just don’t want to talk about it at all right now. It doesn’t really matter to me that other people miss him, I miss him as well.’’ After more silent rummaging, the bag had become half full and started getting heavy. ‘‘I have all I need from here, but I need to go through his locker. Could you help me with that?’’ Don was aware she would not know the locker’s location or combination, but she could surely point him to the person who would. ‘‘She had just finished lunch and was in the rec room on the third floor last I saw her. Do you know how to get there?’’ *What a silly question.* Thought Don. ‘‘Yes, Ms Rider, it’s up the stairs.’’

From the foundations to the teachers’ children-only nursery in the attic of the high-school building extended two sets of big wide granite stairs. The steps had been designed to be noticeably low in height by one of the founders for mysterious reasons. Don grabbed the banister; its colour reminded him of the grey-brown hue and thickness of Mississippi’s bustling waterway, and he propelled himself up the first four steps. With every jump came a feeling of lightness and exertion. Don experienced his ankles flexing and thighs burning pleasantly as he soared above the steps. The lightness was the best part of it; masquerading as conscious attention to risks and slips, Don’s subconscious feeling completely in control and withal free of thoughts.

—–

The third floor housed the oldest pupils, their lockers, and a comfortable but smelly recreation room. Kate sat reading from an electronic ink device initialled ‘R.G.’ on a couch against the small and only window on the western wall. The light had crossed the zenith and cast a bright wedge onto the couch. She had positioned herself with her coat against an armrest and everything but her shoulders and face in the spot of light. The room’s light had been turned off, giving the illuminated spot the appearance of a blaze in the much darker room. Free school hours in the middle of the day were not an anomaly – in fact, every year each student would have schooldays with sizable holes in it due to scheduling conflicts. Students were encouraged to use these hours for studying, but most played cards or football, the location depending on the weather. Kate could hear the breeze outside in the gentle rumbling of green leaves, the sounds flooded the silent room as if attracted by a vacuum.

The door clicked open and her eyes scanned away from the book, adjusting to the room’s lower colour contrast. After a glimpse of her former partner, all that remained was Donald, dressed like any other 12-year-old but sporting some familiar features. ‘‘Hey Don! What a climb, it’s good to see you.’’ ‘‘Hi Katie …  one sec … stairs … backpack … sorry, yeah, I need to get to my brother’s locker’’ ‘‘Yeah of course. I’ll take you; I know the combination too,’’ she said winking at Don, who had finished panting. They started walking towards the locker corridor. ‘‘Is that his reader’’ Don asked. ‘‘Yes, it is, he gave it to me before leaving.’’  ‘‘Oh, do you have many books in it?’’ ‘‘Yes actually, a ton. Before he left, I asked your brother to fill it with all the books in the world worth reading.’‘ ‘‘…’‘ ‘‘So, it has more books that you can count probably.’‘ ‘‘Shut up, I can count to infinity.’‘

The air had started smelling of laundry and metal as they got to the lockers. Kate stopped in front of a medium sized silver lock and rotated the dial mindfully. The space was half occupied by shelving that made different sized cubbies. None of the shelves were occupied but there was a gym bag hanging from the lower shelf and some small books and notebooks resting on the ground.

Katie faced away from the opening and rested her back against the adjacent locker ‘‘Here you go. There is nothing in the top shelves that I can see.’’ Don opened the old bag again and fit the notebooks vertically against its flat side. While deliberating what to do with the gym bag Don heard Katie breathe deeply above him. *The gym bag is clearly too big to fit into the old bag, but big enough to fit my backpack –* *case closed*. ‘‘I’m done here.’‘ ‘‘…’‘ ‘‘Hey Katie, I have all the stuff you can close it now.’‘ ‘‘Oh right.’‘ ‘‘Are you okay?’‘ ‘‘I am okay yeah, why do you ask Don?’‘ ‘‘Well, a lot of people have been asking me if I am okay and I am tired of it because I have to keep saying everything is fine, but I know you miss him as much as me so I want to know how you are feeling. There are way too many books worth reading in the world, you did not want him to leave, just like me.’’ Katie felt overwhelmed by a warm tide of melancholy. Her eyes welled and brightened. The pair hugged as the boy cried softly into her shoulders. When the waves subsided, they walked hand-in-hand back to the rec room.

They spent the rest of her free time together looking over the books in the reader and sharing stories about Don’s brother. At the time of descending the stairs, weighed down by the bags, Don opted for a more careful, single step per footfall approach. The rest of the day went by uneventfully until the siren announced the opening of the gates to the school-bus parking lot. This siren did not coincide with the end of classes, so a group of eager sprinters always assembled by the gates. The goal was to get to their bus the first and thus secure the best seats. Don’s route home was relatively unpopular, so he enjoyed the quiet and winding movements of the bus, sitting almost all the way at the back.

—–

Sometimes Don would sit with his brother on the bus and play games together. The games ranged from school quizzing to ‘‘close your eyes at the beginning of the ride and guess where we are.’’ Many times, they talked about books and read together paragraphs Don’s brother had highlighted. Lately, Don thought back to those conversations and his brother with an innocent and erosive sadness. Don had figured that at some point, his brother would want to build a library and would need someone to build a library with. He knew exactly what type of library it would be. A big sandstone edifice with columns and wide steps in the middle of a desert or a mossier and darker stone temple shrewdly camouflaged in a dense jungle. Don also wondered if they let his brother read at all wherever he was. Presently, Don was not thinking back, or wandering.

This remarkably warm Wednesday, Don looked out from the wide bus windows and thought of nothing in particular. The suburbs diluted into barren terrains, the green gardens of the small houses and the pools and yards of the bigger houses became gradually replaced by disordered piles of masonry and building equipment sitting in the corner of brown and empty rectangles. The journey had no special highlights, only a succession of different landscapes arising and disappearing into the ground like waves. Don entered the meditative state often induced by observing the in- and out-breaths of urbanisation. The sun shone brightly onto the plastic leather seats, making them surprisingly warm and a little sticky. The mind of the young boy was quiet, its slowness matching that of distant objects on the horizon, and the mind’s objects muted, like lonely trees falling in the forest.
