---
title: "Blood Meridian"
author: Arturo
format:
  html:
    css: posts_styles.css
---

This book is a beautiful red sunset on a dry desert, gentle hills and impaled babies; by Cormac McCarthy. Read between 15/09/19 – 14/12/19.

The book has no real plot, we follow the misadventures of the Kid, later Man, as he flees from his home in Atlanta and travels the California desert during the time when the westerners were just starting to get the upper hand on the Indians. The red Indians, the kidnap-your-wife-and-scalp-you-in-front-of-her Indians. This particular scenario does not appear in the novel, but more gruesome and detailed ones certainly do. It is written in a beautiful prose which makes visualizing the scenes effortless. The violence is abundant but is written in a rather impersonal style, it is cruel and violent, but it is never repulsive. The characters are all dirty, sleepless, mad, ideologues and nihilists, fighting for life and death.

Apart from the Kid, there are other recurring characters and we get to know more of them in terms of life details than the Kid through the Kids exploration of the environment and the crew he hangs out with. The principal one is the Judge. The Judge is Big Bald and sometimes naked. He recurs throughout the novel in many forms, as the father benefactor, as the tyrannical father as the mad killer and as the wise wizard. He has a penchant for collecting things but not in the usual way, as he travels like they all travel, very light. He recoups interesting objects or plants and sometimes people; and he takes notes and makes drafts in his notebook until he discards them, the objects, plants or people under observation. This occurs throughout and it serves to build an aura around the character that shrouds him in mystery. The final scenes of the book are perhaps the most salient. For me this was partly because I took a long break before reading the last 10%. The final scene is a banquet celebrated in a classic western saloon. The scene starts with the Kid entering the saloon thirsty, dirty and tired. There he starts drinking and he spots the Judge. This is their first meeting in several years, at least 5. The last time they saw each other, the Kid was in jail and the judge left him there. A girl starts singing as entertainment and a bear dances to her song. Someone kills the bear, and the bears thuds to the ground in a pool of blood. The Judge and the Kid speak, well… the Judge speaks, and he describes how he thinks the night will go. This reminded me of the devil’s ball in Master and Margarita, perpendicularly different vibe but similar eeriness. The party then moves into a barn with a stage and the fiddlers start fiddling. The whores start moving around and the narration takes a slightly drunken turn, things happen very fast and out of the blue, the Judge is naked and dancing an fiddling and he is saying that he will never die, he will never die. The book ends. The epilogue describes how two men walk through the desert by making holes in the sand and stepping on them, one after the other, infinitely towards the red sun.
