---
title: "Con el tiempo a favor"
author: Arturo
format:
  html:
    css: posts_styles.css
---

Salim echó una mirada furtiva a su alrededor para comprobar que nadie le estaba vigilando. Después de cerciorarse, se dirigió con paso decidido hacia los detectores de metales. Estaba seguro de si y sabía que todo saldría como planeado. Mientras andaba se fijaba en la gente que le rodeaba, familias, padres, hermanos, todos despidiéndose y apresurándose hacia el control de seguridad.

Los arcos no supondrían ningún problema y por eso, cuando pitaron, Salim se dio la vuelta con tranquilidad, se quitó el reloj y volvió a pasar. Al terminar el control vio como un hombre con turbante gesticulaba delante de un guardia civil, intentando explicarle que no podía quitarse el turbante, ya que formaba parte de su religión.

Siguiendo las instrucciones que había recibido, Salim se encaminó hacia un extremo de la terminal. Le habían informado de que el paquete que tenía que recoger se encontraba allí, en un baño y una vez dentro pensó que si se había equivocado de extremo de la terminal tendría que correr y no le apetecía nada.

Afortunadamente encontró lo que buscaba, y tan rápido como había entrado salió, esta vez con un maletín de cuero marrón oscuro bajo el brazo.

La suerte le volvió a sonreír y enseguida se encontró delante de su puerta de embarque, como todavía quedaba un rato largo para embarcar se sentó, se preguntó porque se decía embarcar y porque no se había inventado una palabra especifica para los aviones y volvió a mirar a su alrededor.

Esta vez le rodeaba gente que volaría con él, una señora mayor leyendo un libro de autoayuda se sentaba enfrente suyo, cuatro asientos a la izquierda una mujer entre 25 y 30 años tecleaba furiosamente en un portátil, a lo lejos veía llegar una familia entera con dos niños y la pareja de abuelos un poco atrás. Salim suponía que le percibían como un hombre de negocios ya que su único equipaje era un maletín de ejecutivo. Como sabía que quedaba una media hora para el embarque, Salim aprovechó para echar una cabezadita de la que fue despertado por el bullicio que se empezó a formar a su alrededor cuando llegó la hora.

El embarque al avión tampoco le trajo problemas. Esto le pareció raro ya que volando a San Francisco esperaba más medidas de seguridad. Una vez sentado en su sitio descubrió con placer que era el único en su fila, no le hubiera gustado nada estar agarrotado la ultima vez que volaba en avión. Sin embargo le decepcionó no tener la pantallita en el asiento de delante, ya que le habían contado que se podían ver películas y le apetecía mucho comprobar si eso era cierto. Salim se aseguró de que el maletín seguía bajo el asiento de delante y se acomodó para el despegue.

El vuelo duraría unas 14 horas, decidió empezar por dormir la siesta. Cuando despertó, bostezó para destaponarse los oídos y enseguida se arrepintió de haberlo hecho, ya que el ruido era realmente atronador comparado con el silencio del sueño. Como ya se podían utilizar aparatos electrónicos Salim no tardó un segundo en sacar su iPod y ponerse escuchar una lista de reproducción que había creado para la ocasión mezclando canciones folklóricas afganas y sus grupos de rock favoritos, como Jefferson Airplane y Led Zeppelin. Por alguna razón nunca le habían gustado los Beatles. Distraído por la música pasó mas de la mitad del vuelo, cuando llegó la hora de comer pidió pasta, la opción halal, ya que el otro plato contenía carne de cerdo.

Dándose cuenta del tiempo transcurrido Salim se concentró en su tarea. Él estaba sumamente preparado para morir, la idea de contribuir al bien de su pueblo le daba un profundo sentimiento de satisfacción.

La información que había recibido era confusa, lo único que estaba claro es que en ese vuelo iba alguien que tenía que desaparecer.

Ahora el avión sobrevolaba Delaware, o eso indicaba el mapa en las pantallas del avión. Él nunca había oído hablar de Delaware, EEUU para él eran las torres gemelas y las hamburguesas. Se propuso esperar un poco y luego hacer lo que debiera hacer.

En ese momento empezó una película y por curiosidad se puso a verla. Iba de un hombre viudo que compra un zoo por alguna razón de la que Salim no se enteró del todo bien. El corazón de la película estaba en la relación entre el hombre y sus hijos, un adolescente y una niña de seis años que acababan de perder a su madre y necesitaban más cariño que nunca. Cuando terminó la película Salim tenía los ojos brillantes y cansados, y el corazón en un puño. Para calmarse decidió echar una cabezadita, soñó con animales, luego con los personajes de su serie favorita, Modern Family, y luego con nada. Fue despertado por una agradable voz femenina que le decía,

– Señor, hemos aterrizado, usted es el último en el avión-. Ante esto Salim se apresuró a recoger su equipaje y a salir dando las gracias a toda la tripulación que irremediablemente le observaba sonriendo.

Cuando salió de la pasarela y entró en la terminal de San Francisco miró alrededor, y cayó en la cuenta de que se había olvidado detonar la bomba. Por un instante la sangre se le congeló en las venas. Pero solo fue un instante. Acto seguido pensó ¿y qué?

Él, que creía que nunca vería San Francisco ahora estaba parado en medio de su aeropuerto. Inundado por una enorme sensación de vitalidad, hizo una parada rápida en el servicio, cambió los euros que le quedaban a dólares, salió a la calle, se subió al primer taxi que vió y dirigiéndose al conductor dijo, – siga a ese coche-.

Advertisements

Occasionally, some of your visitors may see an advertisement here,\
as well as a [Privacy & Cookies banner](https://en.support.wordpress.com/cookie-widget/) at the bottom of the page.\
You can hide ads completely by upgrading to one of our paid plans.

[UPGRADE NOW](https://wordpress.com/plans/140048366/?feature=no-adverts&utm_campaign=removeadsnotive) [DISMISS MESSAGE](https://ihavetodothisifnot.wordpress.com/2021/01/04/con-el-tiempo-a-favor/#)
