---
title: "Good Old Neon, David Foster Wallace"
author: Arturo
format:
  html:
    css: posts_styles.css
---

This is the first short story I have read by David Foster Wallace. It is included in his last book of short stories called Oblivion. Most of the stories were written in the same handbooks used to draft his final unpublished novel: The Pale King. This group of stories have a common theme which I would call ‘depths of humanity’ but that really is ‘cerebral stories that ask questions about death, consciousness and relationships.’

The story opens inside a car on the road and continues in a very ordered stream of consciousness first person style. The narrator drops the bombshell early; he is planning to kill himself and he is telling you, the reader, all about it. He is going to tell you about the act and he is going to tell you about the motive. The reason to end his life is his fraudulence. Soon-to-be-dead Neal takes us through stages and episodes of his life, always with a fractal view of his behavior and its reflection on others. This fractality is a staple of DFW’s writing and put simply consists of starting a thread and placing new threads inside it to later return to the initial one. Neal tells us he has spent his life always carefully constructing his image, and always feeling guilty for constructing his image. He started doing this deliberately since he first discovered he could lie at an early age. Young Neal had broken a vase and knew his parents would not be angry at him, they never were. However, they would be angry at his sister if she had broken the vase. She was his parents only biological child. When the parents arrived home, Neal confessed in such a way that it seemed he was covering for his sister and thus received praise from his parents. Stratagems like this one became a common feature of his life and little by little his life became more a fake building site than a lived experience.

Sometimes Neal did not realize he was being fraudulent because in tricking those around him he managed to tricked himself. At the moment of realizing his deceitfulness, which re-occurred cyclically, he became distraught and anxious. He tells us about romantic familial and professional relationships ruined due to his fraudulence and he tells us of the things he has tried to stop feeling so fraudulent including attending a megachurch and living a debased lifestyle. He also tells us about Dr Gustafson his therapist, a man he thinks he can lead around, just like everyone else. This last fact makes him sad, because he thought he was getting some real help.

Time is a character in this story, mentioned repeatedly by the soon to be corpse, both in passing and in detail. For the one who is about to die time is truly different. In the final stages of the story, as the car nears the fateful bridge and the Benadryl’s start making Neal sleepy, the narrator switches to David Wallace. For David, Neal was a popular guy in the year above in high school; an accomplished and attractive boy with athletic abilities and a pretty sister. David is trying to fathom what could have led Neal to blast his car against an architectural support and end his life. David wonders what could be crossing the mind of the deceased in the infinite final moments of his life. David decides it was probably a feeling of fraudulence. A feeling that David himself also deals with and conquers every day.

DFW here is at his incisive best. Of all the information about ourselves that we believe to be true, our inner life, only a sliver can be broadcast. Everyone else must look though a keyhole to see inside of us, and lucky for each and everyone of us, the set-up of the room they’re looking into is almost completely up to us. Not thinking about this narrowed lens with which literally everyone else sees us is madness. Simultaneously, thinking too much about the public sliver can cause one to feel crushing fraudulence for living a life where the antechamber does not match the rest of the house. Living a social life in contact with other people requires unspoken agreements regarding the truthfulness of our actions. Living a life in which your actions are only rooted in the desire to curate the keyhole view into your inner life foes against deeply rooted customs, and plants slow growing seeds of insecurity and remorse.

The main point I take away from this story is threefold. First, only an infinitesimal part of our true inner life can be shared. Second, the experiences that we share with others are necessarily curated for self and also public benefit. Third, it is possible to know and reflect about the motivation to die by suicide and nonetheless decide to end one’s life a few month later. DFW said writing fiction ‘is about what it is like to be a human being’ and this is it at its finest.

I highly enjoyed this story, the text was dense but still accessible. I would recommend this story for anyone who wants to explore the deep-end of the mind that wrote Infinite Jest.
