---
title: "Have you ever seen an alligator?"
author: Arturo
format:
  html:
    css: posts_styles.css
---

There is one reason I find alligators fascinating. In a world so taken by activity and a general sense of underlying anxiety they lie completely still. Not a muscle, not a twitch. While people pour into the City of London through the tube stations and the bridges, the alligator slowly opens his mouth. But only because there is no one watching. The alligator might be the only animal that moves more while it sleeps than while it is awake.

Pascal once said “All our unhappiness comes from our inability to sit alone in our room”. This is obviously not literally true but it exaggerates an idea to bring home a general insight. We are often driven to leave our room and seek for the excitement outside. The excitement that doesn’t always turn out the way we wanted. The meeting with friends seems awkward and superfluous, the work hours are not bringing any productivity and the demanding work-out has yet again failed to make you look like the mirror you want. Sitting alone means being with ourselves, un-distracted and calm. Contemplative of the contents of our own mind. Ready to think before we act.

The alligator sits quietly in its room and looks out the window, thinks about the clouds flying high and white, and it wonders if they see him move as he sees them. Then he pours a glass of wine and lies on the couch. He has troubles and worries but, they come and go and thinking deeply he really can’t be dissatisfied. The kids left a long time ago and the house still carries their echoes. He is grateful for that -I wonder if they’re doing okay- he thought. This alligator carried no sorrow and no frustration, he had learnt to look at things under the aspect of eternity. He read Spinoza.

As hundreds of people sit down simultaneously on their swiveling chairs, I like to imagine that some of them, the ones with window access, look outside. And from their vertically enhanced position they stare at the human flow that fills the streets. I like to imagine that a sense of kinship emerges in them and helps them live on through the next 8 hours. -We are all in this together- they think.

The alligator slowly closes its mouth and resumes being absolutely still.
