---
title: "Matter, Iain M. Banks"
author: Arturo
format:
  html:
    css: posts_styles.css
---

Matter was written by Iain M. Banks as part of his Culture series in 2008 and read by me between 22/11/2020 and 21/12/2020. As I read the books in the series, this being my fifth, I find each of them increasingly enjoyable. I am not sure if this reflects an objective quality statement, but what is true is that they are all different and thus at least good for different and interesting reasons.

Matter tracks the life-threads of a high standing family originally living on a Shellworld called Sursamen. Shellworlds are giant spheres which hold smaller spheres within them. Each inter-sphere space is inhabited by one type of alien life form with the core being inhabited by an ancient (millions of years old alien creature called a Xinthian). We focus on the 8th level (from the top) where a human species called the Sarl, make their quai-medieval living. The Sarl are still monarchical and have been at war with the other humans inhabiting the 9th level for several years. The story begins when the prince Ferbin witnesses a heinous betrayal of the crown and decides to escape the planet along with his faithful and quick-witted servant Holse. Meanwhile, Ferbin’s little brother remains on Sursamen, holding the title of prince regent. As a member of the royal family, Ferbin is aware that there are technologically advanced civilizations, the Optimae, outside of their world. Furthermore, Ferbin has a link to one of these civilisations as his sister, Anaplian, was given to mysterious Culture-person in exchange for counsel. The Culture is the unifying link between this series of novels, but they are by no means the only or most powerful civilisation in the galaxy. In fact, the Shellworld is controlled by two alien factions, the Oct and the Aultridia, and the space in which the Shellworld floats is controlled by even more advanced aliens called Nariscene and Morthanveld. Throughout the book we become aware of conflicts at every technological level, each posing an increased risk to the integrity of the Shellworld. The rest of the plot takes the reader along with Ferbin and Holse as they escape the planet and are bounced around between alien holding centres until they find, or rather, are found, by Anaplian. The trio, plus a Mind (a sentient Artificial Intelligence of the Culture), set off for Sursamen with the hope of rescuing the prince regent from the betrayers and avoid an all-out war between higher civilisations.

Now two plot points of interest. First, Ferbin and Holse appear like rabbits in the jungle, impossibly confused at times and gravely in danger at others. From meeting the alien authorities that govern their airspace to travelling through their bureaucratic hoops as mere packages, Ferbin and Holse are differently transformed. The prince, clearly on a recent self-improvement journey (from around page 2), slowly realizes his true standing in the galaxy, and is made aware of the limited impact that he can have. Holse, the servant, continuously marvels at his surroundings and is much more willing to gather new experiences and make efforts to learn after coming to know the galaxy’s true diversity and riches. The second plot point needs a small introduction. There are thousands of Shellworlds like Sursamen in the Galaxy, all built by the same civilization which is long-gone by now. The levels within the Shellworlds have been inhabited by different civilizations through the aeons, some leaving behind wonders for the future to unearth. Ferbin’s little brother, Oramen, is put in charge of an archaeological site that is slowly being revealed by gradual landscape changes occuring on the 9th level. This site seems to be an ancient city with near-impossible architecture and ghostly appearance. This phenomenon, unearthing the wonders of the past is a point in common for all established civilizations. There are records of Babylonian kings carrying out archaeological expeditions to unveil settlements that at the time were hundreds of years old. The descriptions of the ancient yet confusingly advanced architecture are awe-inspiring and the alien streuctures themselves are integrated into the plot with great success.

I thoroughly enjoyed this book so I will continue reading the Culture series with the next in line being Use of Weapons (1990). All books from this series can be read as stand-alone, and if one wishes to continue order does not matter. However, this book is very heavy on the terminology and, as it includes complex diplomacy between aliens, it is better to be acquainted with the general running of the galaxy. I would not recommend starting with this book unless you as a reader are okay with reading  several hundred pages in slight but not debilitating confusion. On the other hand, this book is among the more humorous as it includes a continuously rewarding double-act. This book is definitely worth reading if you are an avid science fiction reader or if you are sci-fi-curious and feel like braving something slightly more complicated than your average best-seller novel.

My subjective rating of this book is 7/10, which means it is very good but not great.
