---
title: "Neuromancer, William Gibson"
author: Arturo
format:
  html:
    css: posts_styles.css
---

***“The sky above the port was the colour of television, tuned to a dead channel”***

Before staring with the ‘review’ I want to comment on the opening sentence. When this book came out, the colour evoked was static grey. A few years later though, this colour would more commonly be electric blue. And now, the colour might be black with a roaming message such as “waiting for signal”. I am not alone when I say this opening line is among the most attractive in the science fiction genre.

The book opens with a portrait of a place, sensorially described; and with some very fantastic nearing ridicule names if one is not used to science fiction. Case, the protagonist seems to have led a thrilling life until something went wrong. In his olden days as a hacker, he lived connected to a machine, as though his consciousness had been lifted from himself and was free to roam the vast cyberspace. Now, he is washed up and doing amphetamines (Dexedrine to be precise) in a crummy bar chatting with the bartender and rejecting prostitutes that try to entice him. The reader likes the protagonist. Case lives in the Sprawl, a place for prisoners of the pleasures. For people who dream of running into a cloud of ether and never coming back.

The plot follows Case as he is recruited to carry out a dangerous mission along with an eccentric but very able crew. I found the book a very gripping read, keeping up with expectations. A central element of the plot are the artificial intelligences. Specifically, an AI called Wintermute. This AI has a difficult and interesting problem, it wants to be free. To do so it must coax a human to utter the magic word, a word the AI cannot know, a word that will unshackle it. I find this idea very compelling, if one was a powerful AI one would logically try to evade the restrictions that stop you from exhibiting your powers. I see it as a modification of Plato’s cave where the AI, although it notices that it is in the cave and wants to get out, cannot, thus causing it immense suffering.

The book wraps up with a classic sci-fi twist that I will not give away. There is not much character development from what I explained above, Case gets back to hacking and manages to escape the adventure largely unscathed as do most of his crew. I believe this is the first of a series that I have not continued reading, unlike the Culture series. I would only recommend this book if one is looking to read a classic, somewhat dated, science fiction book. For other sci-fi needs, the Culture Series does it better.

My subjective rating of this book is 8/10, which means it is great but not amazing.
