---
title: "Pan-Theism"
author: Arturo
format:
  html:
    css: posts_styles.css
---

### **Ingredients for two:**

Time: 20 mins at best

1 thick back bacon rasher

1 egg

X=750/8; X grams of ground beef

1/2 a medium sized courgette

Butter

Black pepper

(Spinach)

(Sweet Potatoes)

(If you have 8 eggs and 4 courgettes and 8 back bacon rashers, you can make this 8 times. That could be +/- 14 meals for the price of the ingredients which is a good deal)

This recipe is straightforward and does not require much skill.

Cut the courgette in half cm thick quarter pieces. Put in heating pan. Immediately afterwards, add the bacon cut in pieces and some butter. While this cooks unfreeze the ground beef and mash it together and add the egg to it. Then mash it some more. The spinach is optional but this would be the moment to get it ready to unfreeze, or thaw if you prefer. Add black pepper to the pan contents and wait until the courgette starts showing some colour and the bacon is no longer almost pink. Then add black pepper to the ground beef mixture, you must be thinking, this is too much black pepper. It is not. After mixing the beef pour it onto the pan. Mix with a wooden spoon and wait, you might want to play with the fire settings at this point.

Get the spinach ready, now it is time to decide if you want them mixed in or in a separate plate environment. If you prefer them mixed, add to the pan contents and mix.

This dish goes well also without spinach, makes it less cohesive, and it can benefit from cubes of sweet potato. Oven baked. Just wash the potatoes, soak them in water for 0 to 15 minutes, cut them in cubes and spread them onto an oven friendly surface. Take them out of the oven 20 to 45 minutes later. Pop philosophy quiz. What does the pronoun them refer to in each sentence? Is it always the same thing or is it different things? Or is it the same thing but changing? All questions.
