---
title: "Personal Knowledge Management enthusiasts"
author: Arturo
format:
  html:
    css: posts_styles.css
---

Roy’s answer is excellent. I also fought with the management of information from the 1997 when I started with Clipper database, Foxpro, Winhelp (hlp - this one I loved so much), Microsoft Compiled HTML Help (chm), Cintanotes, Onenote, Evernote, Zotero, Thebrain, Simplenote, Microsoft Office, Google Drive, Keep, Piggydb, DTsearch, Alltags, Tagging for Windows, File meta, Typora, Logseq, Obsidian, Xmind, Citavi, Tropy, TiddlyWiki, localhost Wordpress, Aeon Timeline, Calibre, Dynalist, Workflowy, Cherrytree, Tagspaces, help systems, saving data to jpg, pdf, use OCR systems, file organizing tools, Copernic Desktop Search, and so many other software and ways to organize, index, tag, visualize my information of text, video, audio, PDF and other formats. Some apps have many useful features to link information, annotate text and images in PDFs, save, convert, index, search data efficiently, manage, display, filter images and other files, most of these will have problems with very large amount of information. I waited features to appear in beloved apps that never appeared, some apps development halted, many became unusable with Gbytes of info, some had ugly UI or had lack of important features even it were attractive. So because of it I have tons of data in Zotero, Cintanotes, Onenote, Evernote, Thebrain I intended to move but requires so much time I would need just doing data moving and organization more than 1 year or more. After that I found Eagle.cool I have 30k files in it. After all I love the linking of information in Thebrain, the beauty and features of Evernote and Onenote, the unique features of Zotero, the way Obsidian and Logseq can manage markdown and annotate PDFs, the way Eagle.cool can filter and preview data. So, trying to preserve information for long term archiving (ex. SingleFile html, PDF portolios, zip, pdf, etc.), tagging and organizing in folders to find all quickly, creating various formats to adapt in multiple apps required so much time. I have more data unorganized and very large number of bookmarks saved and exported in files. Some people use multiple apps to organize information, I liked (theoretically) the way to use a single one and searched the one that have most of features, UI and speed. And was hard. I also tried to organize files in folders and index all with file indexing and searching tool. There are so many ways none are perfect. Lost so many time organizing. Know persons who use just bookmarks or don’t organize just put all the info in a few main folders.\
Cloud search an AI are also great. Cloud space is expensive when you need more.\
I am attracted to clean the save information but requires much time, copy paste, delete, tagging, linking. Later I save information with SingleFile as html put in Eagle.cool, drag full sized images from articles in the same subfolder and create a thumbnailed bookmark also. I still love many note management software, the way it work and display data. But don’t have time to just organize. The time is required for reading. So not very important information is just saved as html and bookmarked and the next is followed. Requires 1 minute. To copy paste, clean, format, tag, link an article requires much more time, to put in a software that locks the information that later reqs years to export and reorganize is so hard. Most of the tried apps became unusable after a time, because of the number of information, files, images, video, audio attachments I put in. Then the migration started. And after a time a realized the new software can’t support one or more features the previous could handle so well. And I was looked for more than that.\
I love information to be in one place, organized, searchable, text with images, videos, audio, scanned papers OCRed, annotated such as PDFs, the usage of mathematical, chemical formulas, graphs, in a possible fastest way. A wish, a dream which is partially satisfied by some apps.\
I think the simplest way (for me putting all information in a big container with folders) is great even not perfect but requires less time and more time remains for reading (till I find a better solution ;)).
