---
title: "The Electric Kool-Aid Acid Test"
author: Arturo
format:
  html:
    css: posts_styles.css
---

Using material collected through the years, Tom Wolfe guides us through the story of the Merry Pranksters. The group formed in the California 60-70s LSD subculture and shook the American ground with their colorful vibrations. The story of the Merry Pranksters is in large part the story of their leader ‘non-leader’ and ‘non-navigator’ Ken Kesey. Kesey is the author of One Flew Over the Cuckoo’s Nest which became the famous movie starring jack Nicholson. Before writing OFOTCN Kesey spent a whole year helping out in what they called at the time an “insane asylum”. The parallel of EKAT with his own life is not weak, the search for freedom and the search for understanding are always present in Kesey’s life.

There is no plot but a sequence of events. Kesey initially gathers the group in his house in La Honda, California. Here they take drugs and produce mediocre psychedelic art. Then they modify a school-bus to travel all across the U.S to the East Coast with the intention of meeting the great psychedelic guru Timothy Leary as well as others. Travellers on the bus are left behind and new ones picked up, being ‘on the bus’ or ‘off the bus’ becomes the way of signalling belonging to the group. And they take a lot of acid. The meeting in the East Coast is disappointing although less jarring than that time they go to a Beatles concert only to cower under the screams of thousands of teenagers. The Merry Pranksters popularize the Acid-Test. This is a party where the kool-aid, a sweet beverage, is spiked with LSD. The Grateful Dead are heavily featured in the book and they often play at Acid-Tests. The group meet the Hell’s Angels motorcycle club and they get along jus fine. Kesey becomes somewhat of a figure and is wanted by the FBI, so he explains that the movement is advancing beyond the use of drugs. This will occur at an event called the Acid-Graduation. The party has an even more cultish sense to it and some guests leave. Kesey gives a speech in a ring of light to a mass of people in the dark. After that, Kesey disappears, is arrested, moves his family to Oregon and starts his court mandated community work in the forests of California.

The book is very well written and does a great job at describing a very particular mood. The LSD mood. Characters are appreciated in bad and good moments of their trips. They are shown to us as they descend to their lowest and most rotten thoughts, and conversely as they realize IT all a.ka. the unity and the beauty of the earth and the people around them. This aspect of the book was interesting as well as just learning about the subculture but for me it was not the golden nugget.

This book is enjoyable at two levels. First there is the history, the LSD tribe is interesting, like peeking at a car-crash. The characters described are somewhat alien but believable, especially under the circumstances which were usually LSD. The author does a good job at recounting the full circle of the Merry Pranksters with feelings included. The second level is the LSD-induced-transcendence and community. The community formed around Kesey and his wife, who cooked and cleaned around the house and took much less acid than the others is at first sight wonderful. The compassion achieved between members and the freedom experienced suggest that the community was a wonderful place to be. But the community comes at a cost. The rules were unspoken but inflexible. One could not even think about infringing the liberties of other people, especially if the other people are expressing themselves, especially if they are doing so while high. You might be thinking, that's no way to live a life, and I would say, you’re right. Telling people they are being stupid without them thinking you are attacking the core of their being is a pillar of society, it’s hard to find nuance with someone who is hallucinating. It is not surprising that a group of young adults that took LSD together felt intensely connected and enlightened, and it is not surprising that the people who go to church together feel a similar way. There is a reason why even the traditions that use psychedelic drugs don’t use them regularly. Blasting your senses and your brain is not good for anyone in the long run.

I believe the book is illuminating regarding the idea of common experience as grounds for community. Experience is a subjective aspect of life that every being with a consciousness must deal with. When a group of people land on a common experience, they form a bond. The bond is only formed of course if there is agreement about the experience, this is what makes it common. The Merry Pranksters remained a group for a long time under the power of this shared experience, the LSD experience. The power of the experience kept them together, until the experience was not common anymore.
