---
title: "The world is very old"
author: Arturo
format:
  html:
    css: posts_styles.css
---

The world is very old,

And so are the rocks and trees.

The world is very old,

So say the Egyptians and the Chinese.

The world is older than this book,

bound in leathery skin.

Older also than this ancient,

And mysterious dried out seed.

The world is big,

from sea to sea,

and it is older,

than you or me.

“The world is very old”

Is an old world saying

Uttered first very long ago.

By a caveman near the fire

Or a pharaoh on his throne

“The world is very old”

Sang the mother to her son.

His eyes sky-bound and mouth open

Asking “just how very old?”

“Old as the rocks and trees,

Or even more we do not know.

And we must care for it together

Because we live in it,

And it is very old”

Scampering around the fire,

Ancient wisdom in his brain,

The young boy finds the star-man,

And ventures to explain.

“The world is very old” The star-man confirms,

“And you should listen to your mother, for she seldom errs”

The star-man turns his gaze, from the blue dome to the earth

“But tell me young man, are you thinking something else?”

He straightens his body and widens his stance, pointing at the horizon.

“Starman, I now know, that the rocks and trees, and birds and bees, are old,

And so is the world, very old. The wisdom is clear, it is not lost on me.

The world is very old, more than you or me.

But Starman I wonder,  if nothing comes from nothing

There must be something no matter how strange

Even older than the world, from which it came to be”

The young man draws a circle on the ground,

A lightly patterned stick moves the soft earth aside.

“Starman, we eat what we find, we wear what we make,

At night we light a fire and protect the tribe,

We matter to ourselves and fight beasts and foes”

The stick rises from the ground, tracing the dimming border

Between brown and blue.

“What good is it for us to know something older still,

Older than rocks and trees and birds and bees.

The lights in the sky are the answer Starman,

they are part of the world we observe

but they must be something separate, they look small and far away,

and why Starman, does it matter?”

The Starman looks pensively, tiredly at the man,

A grown man, wondering about his place, about his mattering.

The stick in his hand a weapon, his body a barrier.

“The world is very old,

And yes the stars are older, much older still,

And yet there is older, the unknown”

The Starman observes the man,

His hands are busy with wicker and sword.

“We come from peoples like us, and our children will follow.

They had ancient wisdom and it was also like ours.

Ancient wisdom is not practical advice, it is a canvas,

A landscape, a world where things can grow.

Now remember this world is very old,

so our mother and grandmothers have been here once before,

made this world for us, and now it is our turn”

The father bows to the Starman, and shuffles back to his tent,

As he lays down to rest, he thinks and feels quite content.

He has grown and yet can grown more.

The sound of mother comes through the door,

A shiver tells him he has been here before.

He merrily gurgles, she shields him from the cold,

Her ancient smooth melody

“The world is very old”
