---
title: "The Closed Circle"
author: Arturo
format:
  html:
    css: posts_styles.css
---

The Closed Circle is the follow-up to Jonathan Coe’s The Rotters Club, a half coming-of-age half British geopolitical commentary novel set in and around Birmingham in the 1970s. The Closed Circle can be read independently, however, I would advise reading the synopsis of TRC found at the end of the book.

The novel spans the years 1999-2004. It starts by showing us what has become of the three main characters in TRC, Benjamin Trotter, Philip Chase and Douglas Anderton. Benjamin is unhappily married to Emily Sandys, a member of the school newspaper editorial team. He works as an accountant and struggles to develop his passion project, a multimedia magnum opus loosely inspired by events in his life. They have no kids and lead a superficially quiet and Christian lifestyle. Philip Chase has become a journalist for Birmingham newspaper and is married to Carol, he has a child, however, with Claire Newman, his ex-wife. Patrick Chase lives with Philip and Carol as Claire only returns to Britain at the beginning of the novel in the year 2000. Doug has become a slightly more successful journalist; he has also married up and now lives in Chelsea with his wife and two kids.

Through the three friends we get access to the wider cast, most of them initially featured in TRC. Ben’s brother Paul is a Labour MP, married with kids. Paul is still friends with Ronald Culpepper the second-best athlete in their school. Claire Newman is still anguished by the disappearance of her sister. Through her, we revisit the Longbridge plant including the characters of Victor Gibbs, Bill Anderton and Roy Slater. Through Philip Chase we reconnect with Steve Richards, who is also settled with kids, and Sean Harding, who has changed most of all.

Added to this mix of familiar characters is the plot-driving centre of the novel, Malvina, a mysterious young woman. There will be no spoilers in this “review”, so the plot won’t be discussed in detail.

As I read this book a few things clicked into place. The Closed Circle, like The Rotters Club is centred around the central themes of political, socioeconomic and cultural differences. These differences are measured in the arguably micro-cosmos of Birmingham and London. This commentary was not apparent to me when I first read TRC (I was 16) but now it jumps out of the page like one of those sculptures that fold within children’s books. Our first introduction to London is through the character of Claire who, after being away from the country finds major changes. London is now a proper 21st century city, the City itself is a place that doesn’t produce things and yet accumulates wealth. For Claire, people move too quickly and drive too aggressively. Birmingham is no different. There, the old Leyland factory, central in TRC, is about to be closed and sold to venture capitalists. The characters reunite for a demonstration in support of the factory workers and for a second it seems that we are back in the 1970s, but not for long.

The early 2000s brought bigger fish to fry for eager demonstrators, this being the impending “unforeseeable” war in the Middle East following the events of September the 11th. I have one memory of that day and it is only special in that it is one of the few memories I still have of my grandfather. He would pick me up at the bus stop after swimming lessons and we would spend the evening together. That day I saw the images on TV, but we did not talk about it and I presume we just played a board games or read in silence. Anyways, some characters seem to be deeply affected and others seem not to notice at all, accurately reflecting, in my opinion, the truth of the situation. The large anti-war demonstrations throughout the country and Europe are featured in the book but of course they are to no avail. This powerlessness of the people is also evident in the all but symbolic renunciation of an efficient welfare state, which is described as a “comically outdated democratic ideal”. Benjamin and Doug themselves embody this renunciation of ideals as Doug has married into an aristocratic family and Benjamin is slowly realizing that his work will take more of him than he can give.

The time we have skipped from TRC to TCC, which includes the Thatcher years, have changed the face and core of the country and the author presents a modest rebirth of politics through the ever-ambiguous Paul Trotter. As a member of New Labour, Paul is not uncomfortable voicing his support for business. However, his allegiance to the party is tested when it comes to voting on the articles of war and, more personally, as he navigates a budding romance with a young mysterious woman.

In TRC, racism is featured but not discussed. Steve Richards, the only black student at the posh private school King Williams, suffers what seem like cruel boyish pranks at the hands of classmates. Reactionary flyers appear at the factory, inciting workers to hate the Irish and the Blacks. These incidents are put in context in this novel, as Philip Chase carries out research on the right-wing nationalist counterculture of the UK. Unfortunately, as race-centric ideologies are on the rise again, I believe we have become desensitised to good narratives of personal suffering like the on Philip tries to piece together. Coe does a great job at keeping the details plot relevant and interesting. If I had to guess, Middle England, the third book of the series, will pickup this thread and give it a more modern twist as the book is set in the 2010s.

I thoroughly enjoyed this book and read it in just 9 days while I let Technopoly by Neil Postman stew. My subjective rating of this book is 8/10, which means it is great but not amazing. I have a personal attachment to this series as TRC is among my all-time favourite books. I would recommend The Rotters Club before The Closed circle and in fact, I gift TRC to anyone as my first gift to them whenever I get that chance, as I think everyone can and should enjoy Jonathan Coe’s flowing, funny and incisive prose
